version: '3'
services:
    web:
        container_name: "petshop"
        image: ambientum/php:7.3-nginx
        ports:
            - '8080:8080'
        volumes:
            - '.:/var/www/app'
        depends_on:
            - 'database'
        links:
            - 'database'
    database:
        container_name: 'petshop-database'
        platform: linux/x86_64
        image: mysql:8
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'secret'
            MYSQL_DATABASE: 'pet'
